"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import mi_interfaz

# Implementing MyFrame1
class mi_interfazMyFrame1( mi_interfaz.MyFrame1 ):
	def __init__( self, parent ):
		mi_interfaz.MyFrame1.__init__( self, parent )
	
	# Handlers for MyFrame1 events.
	def on_print( self, event ):
		self.m_textCtrl1.SetValue("Hola mundo desde una interfaz grafica")
		pass
	
	def on_limpiar( self, event ):
		self.m_textCtrl1.SetValue("")
		pass
	

def main():
	app = wx.App()
	ex = mi_interfazMyFrame1(None)
	ex.Show()
	app.MainLoop()

if __name__ == "__main__":
	main()